<?php

namespace Database\Seeders\GeneralSettings;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $countries = [
            ['initials' => 'AF', 'name' => 'Afghanistan', 'status' => true],
            ['initials' => 'AL', 'name' => 'Albania', 'status' => true],
            ['initials' => 'DZ', 'name' => 'Algeria', 'status' => true],
            ['initials' => 'AS', 'name' => 'American Samoa', 'status' => true],
            ['initials' => 'AD', 'name' => 'Andorra', 'status' => true],
            ['initials' => 'AO', 'name' => 'Angola', 'status' => true],
            ['initials' => 'AI', 'name' => 'Anguilla', 'status' => true],
            ['initials' => 'AQ', 'name' => 'Antarctica', 'status' => true],
            ['initials' => 'AG', 'name' => 'Antigua and Barbuda', 'status' => true],
            ['initials' => 'AR', 'name' => 'Argentina', 'status' => true],
            ['initials' => 'AM', 'name' => 'Armenia', 'status' => true],
            ['initials' => 'AW', 'name' => 'Aruba', 'status' => true],
            ['initials' => 'AU', 'name' => 'Australia', 'status' => true],
            ['initials' => 'AT', 'name' => 'Austria', 'status' => true],
            ['initials' => 'AZ', 'name' => 'Azerbaijan', 'status' => true],
            ['initials' => 'BS', 'name' => 'Bahamas', 'status' => true],
            ['initials' => 'BH', 'name' => 'Bahrain', 'status' => true],
            ['initials' => 'BD', 'name' => 'Bangladesh', 'status' => true],
            ['initials' => 'BB', 'name' => 'Barbados', 'status' => true],
            ['initials' => 'BY', 'name' => 'Belarus', 'status' => true],
            ['initials' => 'BE', 'name' => 'Belgium', 'status' => true],
            ['initials' => 'BZ', 'name' => 'Belize', 'status' => true],
            ['initials' => 'BJ', 'name' => 'Benin', 'status' => true],
            ['initials' => 'BM', 'name' => 'Bermuda', 'status' => true],
            ['initials' => 'BT', 'name' => 'Bhutan', 'status' => true],
            ['initials' => 'BO', 'name' => 'Bolivia', 'status' => true],
            ['initials' => 'BA', 'name' => 'Bosnia and Herzegovina', 'status' => true],
            ['initials' => 'BW', 'name' => 'Botswana', 'status' => true],
            ['initials' => 'BR', 'name' => 'Brazil', 'status' => true],
            ['initials' => 'IO', 'name' => 'British Indian Ocean Territory', 'status' => true],
            ['initials' => 'BN', 'name' => 'Brunei Darussalam', 'status' => true],
            ['initials' => 'BG', 'name' => 'Bulgaria', 'status' => true],
            ['initials' => 'BF', 'name' => 'Burkina Faso', 'status' => true],
            ['initials' => 'BI', 'name' => 'Burundi', 'status' => true],
            ['initials' => 'CV', 'name' => 'Cabo Verde', 'status' => true],
            ['initials' => 'KH', 'name' => 'Cambodia', 'status' => true],
            ['initials' => 'CM', 'name' => 'Cameroon', 'status' => true],
            ['initials' => 'CA', 'name' => 'Canada', 'status' => true],
            ['initials' => 'KY', 'name' => 'Cayman Islands', 'status' => true],
            ['initials' => 'CF', 'name' => 'Central African Republic', 'status' => true],
            ['initials' => 'TD', 'name' => 'Chad', 'status' => true],
            ['initials' => 'CL', 'name' => 'Chile', 'status' => true],
            ['initials' => 'CN', 'name' => 'China', 'status' => true],
            ['initials' => 'CO', 'name' => 'Colombia', 'status' => true],
            ['initials' => 'KM', 'name' => 'Comoros', 'status' => true],
            ['initials' => 'CG', 'name' => 'Congo', 'status' => true],
            ['initials' => 'CD', 'name' => 'Congo (Democratic Republic)', 'status' => true],
            ['initials' => 'CR', 'name' => 'Costa Rica', 'status' => true],
            ['initials' => 'HR', 'name' => 'Croatia', 'status' => true],
            ['initials' => 'CU', 'name' => 'Cuba', 'status' => true],
            ['initials' => 'CY', 'name' => 'Cyprus', 'status' => true],
            ['initials' => 'CZ', 'name' => 'Czech Republic', 'status' => true],
            ['initials' => 'DK', 'name' => 'Denmark', 'status' => true],
            ['initials' => 'DJ', 'name' => 'Djibouti', 'status' => true],
            ['initials' => 'DM', 'name' => 'Dominica', 'status' => true],
            ['initials' => 'DO', 'name' => 'Dominican Republic', 'status' => true],
            ['initials' => 'EC', 'name' => 'Ecuador', 'status' => true],
            ['initials' => 'EG', 'name' => 'Egypt', 'status' => true],
            ['initials' => 'SV', 'name' => 'El Salvador', 'status' => true],
            ['initials' => 'GQ', 'name' => 'Equatorial Guinea', 'status' => true],
            ['initials' => 'ER', 'name' => 'Eritrea', 'status' => true],
            ['initials' => 'EE', 'name' => 'Estonia', 'status' => true],
            ['initials' => 'SZ', 'name' => 'Eswatini', 'status' => true],
            ['initials' => 'ET', 'name' => 'Ethiopia', 'status' => true],
            ['initials' => 'FJ', 'name' => 'Fiji', 'status' => true],
            ['initials' => 'FI', 'name' => 'Finland', 'status' => true],
            ['initials' => 'FR', 'name' => 'France', 'status' => true],
            ['initials' => 'GA', 'name' => 'Gabon', 'status' => true],
            ['initials' => 'GM', 'name' => 'Gambia', 'status' => true],
            ['initials' => 'GE', 'name' => 'Georgia', 'status' => true],
            ['initials' => 'DE', 'name' => 'Germany', 'status' => true],
            ['initials' => 'GH', 'name' => 'Ghana', 'status' => true],
            ['initials' => 'GR', 'name' => 'Greece', 'status' => true],
            ['initials' => 'GD', 'name' => 'Grenada', 'status' => true],
            ['initials' => 'GT', 'name' => 'Guatemala', 'status' => true],
            ['initials' => 'GN', 'name' => 'Guinea', 'status' => true],
            ['initials' => 'GW', 'name' => 'Guinea-Bissau', 'status' => true],
            ['initials' => 'GY', 'name' => 'Guyana', 'status' => true],
            ['initials' => 'HT', 'name' => 'Haiti', 'status' => true],
            ['initials' => 'HN', 'name' => 'Honduras', 'status' => true],
            ['initials' => 'HU', 'name' => 'Hungary', 'status' => true],
            ['initials' => 'IS', 'name' => 'Iceland', 'status' => true],
            ['initials' => 'IN', 'name' => 'India', 'status' => true],
            ['initials' => 'ID', 'name' => 'Indonesia', 'status' => true],
            ['initials' => 'IR', 'name' => 'Iran', 'status' => true],
            ['initials' => 'IQ', 'name' => 'Iraq', 'status' => true],
            ['initials' => 'IE', 'name' => 'Ireland', 'status' => true],
            ['initials' => 'IL', 'name' => 'Israel', 'status' => true],
            ['initials' => 'IT', 'name' => 'Italy', 'status' => true],
            ['initials' => 'JM', 'name' => 'Jamaica', 'status' => true],
            ['initials' => 'JP', 'name' => 'Japan', 'status' => true],
            ['initials' => 'JO', 'name' => 'Jordan', 'status' => true],
            ['initials' => 'KZ', 'name' => 'Kazakhstan', 'status' => true],
            ['initials' => 'KE', 'name' => 'Kenya', 'status' => true],
            ['initials' => 'KI', 'name' => 'Kiribati', 'status' => true],
            ['initials' => 'KP', 'name' => 'Korea (Democratic Peoples Republic)', 'status' => true],
            ['initials' => 'KR', 'name' => 'Korea (Republic)', 'status' => true],
            ['initials' => 'KW', 'name' => 'Kuwait', 'status' => true],
            ['initials' => 'KG', 'name' => 'Kyrgyzstan', 'status' => true],
            ['initials' => 'LA', 'name' => 'Lao Peoples Democratic Republic', 'status' => true],
            ['initials' => 'LV', 'name' => 'Latvia', 'status' => true],
            ['initials' => 'LB', 'name' => 'Lebanon', 'status' => true],
            ['initials' => 'LS', 'name' => 'Lesotho', 'status' => true],
            ['initials' => 'LR', 'name' => 'Liberia', 'status' => true],
            ['initials' => 'LY', 'name' => 'Libya', 'status' => true],
            ['initials' => 'LI', 'name' => 'Liechtenstein', 'status' => true],
            ['initials' => 'LT', 'name' => 'Lithuania', 'status' => true],
            ['initials' => 'LU', 'name' => 'Luxembourg', 'status' => true],
            ['initials' => 'MG', 'name' => 'Madagascar', 'status' => true],
            ['initials' => 'MW', 'name' => 'Malawi', 'status' => true],
            ['initials' => 'MY', 'name' => 'Malaysia', 'status' => true],
            ['initials' => 'MV', 'name' => 'Maldives', 'status' => true],
            ['initials' => 'ML', 'name' => 'Mali', 'status' => true],
            ['initials' => 'MT', 'name' => 'Malta', 'status' => true],
            ['initials' => 'MH', 'name' => 'Marshall Islands', 'status' => true],
            ['initials' => 'MR', 'name' => 'Mauritania', 'status' => true],
            ['initials' => 'MU', 'name' => 'Mauritius', 'status' => true],
            ['initials' => 'MX', 'name' => 'Mexico', 'status' => true],
            ['initials' => 'FM', 'name' => 'Micronesia (Federated States of)', 'status' => true],
            ['initials' => 'MD', 'name' => 'Moldova', 'status' => true],
            ['initials' => 'MC', 'name' => 'Monaco', 'status' => true],
            ['initials' => 'MN', 'name' => 'Mongolia', 'status' => true],
            ['initials' => 'ME', 'name' => 'Montenegro', 'status' => true],
            ['initials' => 'MA', 'name' => 'Morocco', 'status' => true],
            ['initials' => 'MZ', 'name' => 'Mozambique', 'status' => true],
            ['initials' => 'MM', 'name' => 'Myanmar', 'status' => true],
            ['initials' => 'NA', 'name' => 'Namibia', 'status' => true],
            ['initials' => 'NR', 'name' => 'Nauru', 'status' => true],
            ['initials' => 'NP', 'name' => 'Nepal', 'status' => true],
            ['initials' => 'NL', 'name' => 'Netherlands', 'status' => true],
            ['initials' => 'NZ', 'name' => 'New Zealand', 'status' => true],
            ['initials' => 'NI', 'name' => 'Nicaragua', 'status' => true],
            ['initials' => 'NE', 'name' => 'Niger', 'status' => true],
            ['initials' => 'NG', 'name' => 'Nigeria', 'status' => true],
            ['initials' => 'NO', 'name' => 'Norway', 'status' => true],
            ['initials' => 'OM', 'name' => 'Oman', 'status' => true],
            ['initials' => 'PK', 'name' => 'Pakistan', 'status' => true],
            ['initials' => 'PW', 'name' => 'Palau', 'status' => true],
            ['initials' => 'PS', 'name' => 'Palestine', 'status' => true],
            ['initials' => 'PA', 'name' => 'Panama', 'status' => true],
            ['initials' => 'PG', 'name' => 'Papua New Guinea', 'status' => true],
            ['initials' => 'PY', 'name' => 'Paraguay', 'status' => true],
            ['initials' => 'PE', 'name' => 'Peru', 'status' => true],
            ['initials' => 'PH', 'name' => 'Philippines', 'status' => true],
            ['initials' => 'PL', 'name' => 'Poland', 'status' => true],
            ['initials' => 'PT', 'name' => 'Portugal', 'status' => true],
            ['initials' => 'QA', 'name' => 'Qatar', 'status' => true],
            ['initials' => 'RO', 'name' => 'Romania', 'status' => true],
            ['initials' => 'RU', 'name' => 'Russian Federation', 'status' => true],
            ['initials' => 'RW', 'name' => 'Rwanda', 'status' => true],
            ['initials' => 'KN', 'name' => 'Saint Kitts and Nevis', 'status' => true],
            ['initials' => 'LC', 'name' => 'Saint Lucia', 'status' => true],
            ['initials' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'status' => true],
            ['initials' => 'WS', 'name' => 'Samoa', 'status' => true],
            ['initials' => 'SM', 'name' => 'San Marino', 'status' => true],
            ['initials' => 'ST', 'name' => 'Sao Tome and Principe', 'status' => true],
            ['initials' => 'SA', 'name' => 'Saudi Arabia', 'status' => true],
            ['initials' => 'SN', 'name' => 'Senegal', 'status' => true],
            ['initials' => 'RS', 'name' => 'Serbia', 'status' => true],
            ['initials' => 'SC', 'name' => 'Seychelles', 'status' => true],
            ['initials' => 'SL', 'name' => 'Sierra Leone', 'status' => true],
            ['initials' => 'SG', 'name' => 'Singapore', 'status' => true],
            ['initials' => 'SK', 'name' => 'Slovakia', 'status' => true],
            ['initials' => 'SI', 'name' => 'Slovenia', 'status' => true],
            ['initials' => 'SB', 'name' => 'Solomon Islands', 'status' => true],
            ['initials' => 'SO', 'name' => 'Somalia', 'status' => true],
            ['initials' => 'ZA', 'name' => 'South Africa', 'status' => true],
            ['initials' => 'SS', 'name' => 'South Sudan', 'status' => true],
            ['initials' => 'ES', 'name' => 'Spain', 'status' => true],
            ['initials' => 'LK', 'name' => 'Sri Lanka', 'status' => true],
            ['initials' => 'SD', 'name' => 'Sudan', 'status' => true],
            ['initials' => 'SR', 'name' => 'Suriname', 'status' => true],
            ['initials' => 'SE', 'name' => 'Sweden', 'status' => true],
            ['initials' => 'CH', 'name' => 'Switzerland', 'status' => true],
            ['initials' => 'SY', 'name' => 'Syrian Arab Republic', 'status' => true],
            ['initials' => 'TW', 'name' => 'Taiwan', 'status' => true],
            ['initials' => 'TJ', 'name' => 'Tajikistan', 'status' => true],
            ['initials' => 'TZ', 'name' => 'Tanzania', 'status' => true],
            ['initials' => 'TH', 'name' => 'Thailand', 'status' => true],
            ['initials' => 'TL', 'name' => 'Timor-Leste', 'status' => true],
            ['initials' => 'TG', 'name' => 'Togo', 'status' => true],
            ['initials' => 'TO', 'name' => 'Tonga', 'status' => true],
            ['initials' => 'TT', 'name' => 'Trinidad and Tobago', 'status' => true],
            ['initials' => 'TN', 'name' => 'Tunisia', 'status' => true],
            ['initials' => 'TR', 'name' => 'Turkey', 'status' => true],
            ['initials' => 'TM', 'name' => 'Turkmenistan', 'status' => true],
            ['initials' => 'TV', 'name' => 'Tuvalu', 'status' => true],
            ['initials' => 'UG', 'name' => 'Uganda', 'status' => true],
            ['initials' => 'UA', 'name' => 'Ukraine', 'status' => true],
            ['initials' => 'AE', 'name' => 'United Arab Emirates', 'status' => true],
            ['initials' => 'GB', 'name' => 'United Kingdom', 'status' => true],
            ['initials' => 'US', 'name' => 'United States', 'status' => true],
            ['initials' => 'UY', 'name' => 'Uruguay', 'status' => true],
            ['initials' => 'UZ', 'name' => 'Uzbekistan', 'status' => true],
            ['initials' => 'VU', 'name' => 'Vanuatu', 'status' => true],
            ['initials' => 'VE', 'name' => 'Venezuela', 'status' => true],
            ['initials' => 'VN', 'name' => 'Viet Nam', 'status' => true],
            ['initials' => 'VG', 'name' => 'Virgin Islands (British)', 'status' => true],
            ['initials' => 'VI', 'name' => 'Virgin Islands (U.S.)', 'status' => true],
            ['initials' => 'WF', 'name' => 'Wallis and Futuna', 'status' => true],
            ['initials' => 'EH', 'name' => 'Western Sahara', 'status' => true],
            ['initials' => 'YE', 'name' => 'Yemen', 'status' => true],
            ['initials' => 'ZM', 'name' => 'Zambia', 'status' => true],
            ['initials' => 'ZW', 'name' => 'Zimbabwe', 'status' => true],
        ];

        // Insertar los datos en la tabla "countries"
        DB::table('countries')->insert($countries);
    }
}
